CREATE TABLE HES_CIPS_ELIXHAUSER AS
SELECT c.CIPS_NUMBER, ELIXHAUSER_CODE FROM
HES_INPATIENT_CIPS c
INNER JOIN HES_INPATIENT_EPISODE e
ON c.cips_number = e.cips_number
INNER JOIN HES_INPATIENT_EPISODE_DIAG d
ON e.episode_number = d.episode_number
INNER JOIN ELIXHAUSER_CODES ex
ON D.DIAG_CODE = ex.ALT_CODE
GROUP BY c.cips_number, ELIXHAUSER_CODE;

CREATE INDEX CIPS_ELIX_NUM ON HEPI.HES_CIPS_ELIXHAUSER(CIPS_NUMBER);

CREATE INDEX CIPS_ELIX_CODE ON HEPI.HES_CIPS_ELIXHAUSER(ELIXHAUSER_CODE);