
CREATE TABLE HES_MORTALITY(
extract_hesid VARCHAR2(32),
dod DATE,
dor DATE,
commune VARCHAR2(6),
nhs_ind NUMBER(1,0), 
soal  varchar2(10)
) TABLESPACE HEPI;

CREATE TABLE HES_MORTALITY_CAUSE(
extract_hesid VARCHAR2(32),
cause varchar2(4),
is_primary NUMBER(1,0)
) TABLESAPCE HEPI;

CREATE TABLE HES_MORTALITY_OPTIM AS 
SELECT m.*, 
CASE p.sex WHEN 1 THEN 'M' WHEN 2 THEN 'F' ELSE 'U' END sex,
CASE WHEN EXTRACT(MONTH FROM m.DOD)>=4 THEN EXTRACT(YEAR FROM m.DOD) WHEN EXTRACT(MONTH FROM m.DOD) < 4 THEN EXTRACT(YEAR FROM m.DOD)-1 ELSE NULL END hes_year,
CASE 
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 0 AND 4 THEN '0-4'
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 5 AND 15 THEN '5-15'
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 16 AND 24 THEN '16-24'
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 25 AND 39 THEN '25-39'
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 40 AND 59 THEN '40-59'
WHEN floor(months_between(m.dod, p.dob) /12) BETWEEN 60 AND 74 THEN '60-74'
WHEN floor(months_between(m.dod, p.dob) /12) >= 75 THEN '75+'
ELSE NULL
END age_group,
imd.quintile AS imd_quintile
FROM 
HES_MORTALITY m 
LEFT JOIN
IMD_2010 imd
ON m.soal = imd.lsoa01cd
LEFT JOIN 
HES_PATIENT p
ON p.extract_hesid = m.extract_hesid;

CREATE INDEX M_EXTRACT_HESID ON HES_MORTALITY_OPTIM (EXTRACT_HESID);
CREATE INDEX M_DOD ON HES_MORTALITY_OPTIM (DOD);
CREATE INDEX M_SOAL ON HES_MORTALITY_OPTIM (SOAL);
CREATE BITMAP INDEX M_HES_YEAR ON HES_MORTALITY_OPTIM (HES_YEAR);
CREATE BITMAP INDEX M_AGE_GROUP ON HES_MORTALITY_OPTIM (AGE_GROUP);
CREATE BITMAP INDEX M_SEX ON HES_MORTALITY_OPTIM (SEX);
CREATE BITMAP INDEX M_IMD ON HES_MORTALITY_OPTIM (IMD_QUINTILE);