CREATE TABLE NHS_GEOGRAPHY_IMD2010 AS
SELECT g.*, NTILE(5) OVER (ORDER BY IMD2010_OVERALL_RANK) AS imd_quintile, NTILE(10) OVER (ORDER BY IMD2010_OVERALL_RANK) AS imd_decile FROM (   
SELECT g.*, imd.overall_rank as IMD2010_OVERALL_RANK FROM NHS_GEOGRAPHY g
JOIN IMD_2010 imd 
ON imd.lsoa_code = g.lsoa11cd)g;