DROP TABLE HES_PATIENT PURGE;
CREATE TABLE HES_PATIENT(
extract_hesid  varchar2(32),
dob  DATE,
ethnos  varchar2(1),
sex  NUMBER(1,0)
);

DROP TABLE HES_INPATIENT_CIPS PURGE;
CREATE TABLE HES_INPATIENT_CIPS(
cips_number INTEGER,
extract_hesid  varchar2(32),
admidate  DATE,
admimeth  NUMBER(2,0),
admisorc  NUMBER(2,0),
admincat  NUMBER(2,0),
admistat  NUMBER(1,0),
classpat  NUMBER(1,0),
elecdate  DATE,
elecdur  INTEGER,
disdate  DATE,
disdest  NUMBER(2,0),
disreadydate  DATE,
dismeth  NUMBER(1,0),
soal  varchar2(10),
hes_year NUMBER(4,0),
age_group VARCHAR2(10) 
);

DROP TABLE HES_INPATIENT_SPELL PURGE;
CREATE TABLE HES_INPATIENT_SPELL(
spell_number INTEGER,
cips_number INTEGER,
extract_hesid  varchar2(32),
admidate  DATE,
admimeth  NUMBER(2,0),
admisorc  NUMBER(2,0),
admincat  NUMBER(2,0),
admistat  NUMBER(1,0),
classpat  NUMBER(1,0),
elecdate  DATE,
elecdur  INTEGER,
disdate  DATE,
disdest  NUMBER(2,0),
disreadydate  DATE,
dismeth  NUMBER(1,0),
purcode  varchar2(6),
procode  varchar2(6),
protype  varchar2(200),
preferer  varchar2(16),
referorg  varchar2(16),
soal  varchar2(10),
hes_year NUMBER(4,0),
age_group VARCHAR2(10) 
);

DROP TABLE HES_INPATIENT_EPISODE PURGE;
CREATE TABLE HES_INPATIENT_EPISODE(
episode_number INTEGER,
spell_number INTEGER,
cips_number INTEGER,
extract_hesid  varchar2(32),
epistart  DATE,
epiend  DATE,
epidur  INTEGER,
epiorder  NUMBER(2,0),
epitype  NUMBER(1,0),
mainspef  varchar2(4),
tretspef  varchar2(4),
operstat  NUMBER(1,0),
posopdur  INTEGER,
preopdur  INTEGER,
sitetret  varchar2(5),
hrgcode  varchar2(5),
hrgversion  varchar2(5),
pconsult  varchar2(16),
epikey  INTEGER,
soal  varchar2(10),
hes_year NUMBER(4,0),
age_group VARCHAR2(10) 
) TABLESPACE HEPI;

DROP TABLE HES_INPATIENT_EPISODE_DIAG PURGE;
CREATE TABLE HES_INPATIENT_EPISODE_DIAG(
episode_number INTEGER,
diag_code  varchar2(4),
is_primary NUMBER(1,0)
);

DROP TABLE HES_INPATIENT_EPISODE_PROC PURGE;
CREATE TABLE HES_INPATIENT_EPISODE_PROC(
episode_number INTEGER,
procedure_code  varchar2(4),
procedure_date DATE,
is_primary NUMBER(1,0)
);

CREATE INDEX CIPS_EXTRACT_HESID ON HES_INPATIENT_CIPS (EXTRACT_HESID);
CREATE INDEX CIPS_ADMIDATE ON HES_INPATIENT_CIPS (ADMIDATE);
CREATE BITMAP INDEX CIPS_ADMIMETH ON HES_INPATIENT_CIPS (ADMIMETH);
CREATE BITMAP INDEX CIPS_ADMISORC ON HES_INPATIENT_CIPS (ADMISORC);
CREATE BITMAP INDEX CIPS_DISDEST ON HES_INPATIENT_CIPS (DISDEST);
CREATE INDEX CIPS_DISDATE ON HES_INPATIENT_CIPS (DISDATE);
CREATE INDEX CIPS_DISMETH ON HES_INPATIENT_CIPS (DISMETH);
CREATE INDEX CIPS_SOAL ON HES_INPATIENT_CIPS (SOAL);
CREATE BITMAP INDEX CIPS_HES_YEAR ON HES_INPATIENT_CIPS (HES_YEAR);
CREATE BITMAP INDEX CIPS_AGE_GROUP ON HES_INPATIENT_CIPS (AGE_GROUP);


CREATE INDEX SPELL_EXTRACT_HESID ON HES_INPATIENT_SPELL (EXTRACT_HESID);
CREATE INDEX SPELL_CIPS_NUMBER ON HES_INPATIENT_SPELL (CIPS_NUMBER);
CREATE INDEX SPELL_ADMIDATE ON HES_INPATIENT_SPELL (ADMIDATE);
CREATE BITMAP INDEX SPELL_ADMIMETH ON HES_INPATIENT_SPELL (ADMIMETH);
CREATE BITMAP INDEX SPELL_ADMISORC ON HES_INPATIENT_SPELL (ADMISORC);
CREATE BITMAP INDEX SPELL_DISDEST ON HES_INPATIENT_SPELL (DISDEST);
CREATE BITMAP INDEX SPELL_DISMETH ON HES_INPATIENT_SPELL (DISMETH);
CREATE INDEX SPELL_DISDATE ON HES_INPATIENT_SPELL (DISDATE);
CREATE INDEX SPELL_SOAL ON HES_INPATIENT_SPELL (SOAL);
CREATE BITMAP INDEX SPELL_HES_YEAR ON HES_INPATIENT_SPELL (HES_YEAR);
CREATE BITMAP INDEX SPELL_AGE_GROUP ON HES_INPATIENT_SPELL (AGE_GROUP);


CREATE INDEX EPISODE_EXTRACT_HESID ON HES_INPATIENT_EPISODE (EXTRACT_HESID);
CREATE INDEX EPISODE_CIPS_NUMBER ON HES_INPATIENT_EPISODE (CIPS_NUMBER);
CREATE INDEX EPISODE_SPELL_NUMBER ON HES_INPATIENT_EPISODE (SPELL_NUMBER);
CREATE INDEX EPISODE_EPISTART ON HES_INPATIENT_EPISODE (EPISTART);
CREATE INDEX EPISODE_EPIEND ON HES_INPATIENT_EPISODE (EPIEND);
CREATE BITMAP INDEX EPISODE_EPIORDER ON HES_INPATIENT_EPISODE (EPIORDER);
CREATE BITMAP INDEX EPISODE_EPITYPE ON HES_INPATIENT_EPISODE (EPITYPE);
CREATE BITMAP INDEX EPISODE_MAINSPEF ON HES_INPATIENT_EPISODE (MAINSPEF);
CREATE BITMAP INDEX EPISODE_TRETSPEF ON HES_INPATIENT_EPISODE (TRETSPEF);
CREATE INDEX EPISODE_EPIKEY ON HES_INPATIENT_EPISODE (EPIKEY);
CREATE INDEX EPISODE_SOAL ON HES_INPATIENT_EPISODE (SOAL);
CREATE BITMAP INDEX EPISODE_HES_YEAR ON HES_INPATIENT_EPISODE (HES_YEAR);
CREATE BITMAP INDEX EPISODE_AGE_GROUP ON HES_INPATIENT_EPISODE (AGE_GROUP);


CREATE INDEX EPI_DIAG_EPISODE_NUMBER ON HES_INPATIENT_EPISODE_DIAG (EPISODE_NUMBER);
CREATE INDEX EPI_DIAG_ICD ON HES_INPATIENT_EPISODE_DIAG (DIAG_CODE);
CREATE BITMAP INDEX EPI_DIAG_PRIMARY ON HES_INPATIENT_EPISODE_DIAG (IS_PRIMARY);
CREATE INDEX diag_substr_1 ON HES_INPATIENT_EPISODE_DIAG(substr(diag_code,1,1));

CREATE INDEX EPI_PROC_EPISODE_NUMBER ON HES_INPATIENT_EPISODE_PROC (EPISODE_NUMBER);
CREATE INDEX EPI_PROC_OPCS ON HES_INPATIENT_EPISODE_PROC (PROCEDURE_CODE);
CREATE INDEX EPI_PROC_DATE ON HES_INPATIENT_EPISODE_PROC (PROCEDURE_DATE);
CREATE BITMAP INDEX EPI_PROC_PRIMARY ON HES_INPATIENT_EPISODE_PROC (IS_PRIMARY);
CREATE INDEX proc_substr_3 ON HES_INPATIENT_EPISODE_PROC(substr(procedure_code,1,3));
